lib/use_packwerk/private.rb
I think this will be helpful and necessary for moving packs to be child packs, as some packs have .yml files that need to be moved too.
This already works for individual files, but just not directories.
=> Allow UsePackwerk to move all files, not just ruby files

Gemfile.lock, lib/use_packwerk.rb, lib/use_packwerk/cli.rb, lib/use_packwerk/logging.rb, lib/use_packwerk/private.rb, spec/spec_helper.rb, spec/use_packwerk_spec.rb, use_packwerk.gemspec
I realized a `bin/use_packwerk move_to_parent packs/parent_pack packs/child_pack` command will be sorely needed if we don't want folks to follow a somewhat convoluted, multi-step process to make a pack a child pack. I am hoping this will lead to a lot more exploration for users.
This PR in ZP demonstrates the use: https://github.com/Gusto/zenpayroll/pull/146088
=> Add UsePackwerk.move_to_parent! API

.github/workflows/ci.yml, .rubocop.yml, Gemfile.lock, lib/use_packwerk.rb, lib/use_packwerk/cli.rb, lib/use_packwerk/code_ownership_post_processor.rb, lib/use_packwerk/configuration.rb, lib/use_packwerk/logging.rb, lib/use_packwerk/per_file_processor_interface.rb, lib/use_packwerk/private.rb, lib/use_packwerk/private/file_move_operation.rb, lib/use_packwerk/private/pack_relationship_analyzer.rb, lib/use_packwerk/rubocop_post_processor.rb, spec/spec_helper.rb, spec/use_packwerk_spec.rb, use_packwerk.gemspec
- add rubocop
- initial rubocop autocorrect
- more manual fixes
=> Add rubocop

.github/workflows/publish.yml
This fork looks like a better maintained one: https://github.com/discourse/publish-rubygems-action
It looks like it solves the problem of setting git config in order to properly push a tag.
=> Use discourse fork of publish-rubygems-action

Gemfile.lock, lib/use_packwerk/private/interactive_cli/use_cases/update_deprecations.rb, lib/use_packwerk/private/interactive_cli/use_cases/validate.rb, use_packwerk.gemspec
This fixes an issue where we weren't forwarding terminal output to the main terminal, resulting in an unexpected lack of visible progress.
```
~/workspace/zenpayroll - (main) $ bin/packs
Hello! What would you like to do? Run bin/packwerk update-deprecations
Running via Spring preloader in process 49546
~/workspace/zenpayroll - (main) $ 
```
```
~/workspace/zenpayroll - (main) $ bin/packs
Hello! What would you like to do? Run bin/packwerk update-deprecations
[TEST PROF INFO] Spring detected
Running via Spring preloader in process 49853
📦 Packwerk is inspecting X files
📦 Finished in 8.58 seconds
No offenses detected
✅ `deprecated_references.yml` has been updated.
```
=> Fix issue with bin/packs command having no output

.github/workflows/cd.yml
https://docs.github.com/en/actions/using-workflows/using-github-cli-in-workflows
Github actions can use the GH CLI. I think using github's officially supported API will be a better option.
Note we were previously using https://github.com/softprops/action-gh-release
We are not using any of its more advanced features so I think the GH CLI will work just fine for now, and is easier to understand.
=> Use GH CLI to create GH release rather than rely on open source action

.github/workflows/cd.yml, Gemfile.lock, use_packwerk.gemspec
This gets rid of a deprecation warning in the CD pipeline, e.g.: https://github.com/rubyatscale/use_packwerk/actions/runs/3321794584
```
deploy
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-command
```
=> Use updated publish-rubygems-action

Gemfile.lock, README.md, advanced_usage.md, bin/packs, bin/use_packwerk, lib/use_packwerk/cli.rb, lib/use_packwerk/user_event_logger.rb, spec/use_packwerk_spec.rb, use_packwerk.gemspec
This PR moves us to a single CLI tool, `bin/packs`. If any args are supplied, it dispatches to the "manual" mode, letting this CLI tool be used manually and interactively.
=> Consolidate bin/use_packwerk into bin/packs

Gemfile.lock, lib/use_packwerk/cli.rb, lib/use_packwerk/code_ownership_post_processor.rb, lib/use_packwerk/per_file_processor_interface.rb, lib/use_packwerk/private.rb, lib/use_packwerk/private/interactive_cli/use_cases/regenerate_rubocop_todo.rb, lib/use_packwerk/private/packwerk_wrapper/offenses_aggregator_formatter.rb, lib/use_packwerk/rubocop_post_processor.rb, lib/use_packwerk/user_event_logger.rb, sorbet/rbi/gems/rubocop-packs@0.0.27.rbi, spec/spec_helper.rb, spec/use_packwerk_spec.rb, use_packwerk.gemspec
Best viewed commit by commit
- Add bin/packs regenerate_rubocop_todo
- Reorganize how spec file move operations are constructed so we can pass in file move operations to per file processor after move files
- use updated RP API
- remove mentions of PP and other outdated APIs
- update API to after_move_files to take in file operations
- run rubocop regenerate_todo after moving files
- Tell thor private methods should not be commands
- bump rubocop-packs
- rubocop
- Add allow so we do not attempt to execute rubocop during specs
- Clean up test output
- bump version
=> Allow bin/packs move and bin/packs make_public to regenerate the rubocop TODO

Gemfile.lock, lib/use_packwerk/private/interactive_cli/team_selector.rb, spec/use_packwerk/private/interactive_cli_spec.rb, use_packwerk.gemspec
Problem
-------
If I run `bin/packs` and create a new pack, when I get to the team list it's in what looks like a random order.
```bash
❯ bin/packs
Hello! What would you like to do? Create a new pack
What should the name of your pack be? packs/whatever
Please select a team owner (Press ↑/↓/←/→ arrow to move, Enter to select and letters to filter)
‣ Team 5
Apples Team
Search
Other Team
```
We do have autocomplete with typing but you can also scroll through by arrow keys. If you use the latter method, it might be nice to have these in order.
Solution
--------
Sort the list of teams by name before sending to the prompt.
```bash
❯ bin/packs
Hello! What would you like to do? Create a new pack
What should the name of your pack be? packs/whatever
Please select a team owner (Press ↑/↓/←/→ arrow …
```
=> Alphabetize the Team list for easier selection

Gemfile.lock, lib/use_packs/private/interactive_cli/pack_selector.rb, lib/use_packs/private/interactive_cli/team_selector.rb, lib/use_packs/private/interactive_cli/use_cases/visualize.rb, spec/use_packs/private/interactive_cli_spec.rb, use_packs.gemspec
Catches the case when someone uses enter rather than space to select a team/name, warns, and cycles the process.
=> Catch empty selection on visualize

Gemfile, Gemfile.lock, lib/use_packs/private/packwerk_wrapper/offenses_aggregator_formatter.rb, sorbet/rbi/gems/packwerk@2.2.1-8476bb3cd5452765ad452d36aa45ae724f1d44f5.rbi, use_packs.gemspec
This is temporary! Will allow us to get on packwerk `main` in the gusto monolith.
=> Use T.untyped instead of Packwerk::OffenseCollection temporarily

Gemfile.lock, lib/use_packs/private.rb, lib/use_packs/private/packwerk_wrapper.rb, lib/use_packs/user_event_logger.rb, spec/use_packs_spec.rb, use_packs.gemspec
Adding a dependency can result in a cycle, so we automatically run validate to give users that feedback.
=> Run bin/packwerk validate when adding a dependency

Gemfile.lock, lib/use_packs/cli.rb, use_packs.gemspec
Packwerk 3 doesn't permit arguments to be passed into `bin/packwerk update-todo`
=> Update docs on bin/packs update

advanced_usage.md
`$ bundle binstubs packs`
=>
`There are no executables for the gem packs.`
`bundle binstubs use_packs` correctly creates the `bin/packs` folder.
=> Fix binstubs commands

Gemfile.lock, sorbet/rbi/gems/rubocop-packs@0.0.33.rbi, sorbet/rbi/gems/rubocop-packs@0.0.37.rbi, spec/use_packs_spec.rb
This is mostly a revert, as we need to address performance issues associated with multiple `packs/*/.rubocop.yml`.
Commits:
- Revert "Bump rubocop-packs (#79)"
- bump rubocop packs
=> Bump rubocop-packs

Gemfile.lock, lib/use_packs/private.rb, spec/use_packs_spec.rb, use_packs.gemspec
Now possible with the new `code_ownership`.
=> Set owner key to top-level of new pack

README.md, lib/packs.rb, lib/packs/cli.rb, lib/packs/private/interactive_cli/use_cases/query.rb, lib/packs/private/pack_relationship_analyzer.rb, lib/packs/user_event_logger.rb, spec/packs/private/cli_spec.rb, spec/packs_spec.rb
This PR merges the code of `list_top_dependency_violations` and `list_top_privacy_violations` into a more generic `list_top_violations` command receiving a type. Then on a second commit it adds support for listing top architecture violations leveraging the same code as the other two.
=> Add support for listing top architecture violations

Gemfile.lock, lib/packs.rb, lib/packs/cli.rb, lib/packs/private.rb, packs.gemspec, spec/packs/private/cli_spec.rb, spec/packs_spec.rb
I decided to send this PR because in our project we're not ready to enforce privacy in many packs just yet and I've had to repeatedly keep deleting the autogenerated `public/TODO.md` file each time I create a new pack or move files to an already existing pack without enforcing privacy.
This PR:
* Allows passing `--no-enforce-privacy` to `create` to optionally create a pack without enforcing privacy in which case the public dir won't be forcefully created.
* When moving files to a pack which doesn't enforce privacy, it won't forcefully create the public dir either.
I was also adding a `-P` option to both `create` and `move` commands to allow skipping automatic creation of `public/TODO.md` when moving files to a pack not having a public directory, or when creating a pack without enforcing …
=> Allow skipping public dir creation when creating pack or moving files

lib/packs/private.rb
I was running into this problem when upgrading to the latest packs (0.0.24 to 0.0.29):
```
❯ DISABLE_SPRING=1 bin/packs lint_package_todo_yml_files
📦 Packwerk is inspecting 30396 files
............
✅ `package_todo.yml` has been updated.
/Users/josh.nichols/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/packs-0.0.29/lib/packs/private.rb:438:in `diff_package_todo_yml': undefined method `mktmpdir' for Dir:Class (NoMethodError)
dir_containing_contents_before = Dir.mktmpdir
^^^^^^^^^
Did you mean?  mkdir
from /Users/josh.nichols/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.10983/lib/types/private/methods/call_validation.rb:256:in `bind_call'
from /Users/josh.nichols/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/sorbet-runtime-0.5.10983/lib/types/private/methods/call_valida …
```
=> Make sure to require tmpdir before using mktmpdir

lib/packs/private.rb
Currently we check to see if there's a readme before the pack move. We need to check after the move.
=> Fix: move readme check to later in the process

lib/packs/cli.rb, lib/packs/private.rb, lib/packs/private/interactive_cli/use_cases/get_info.rb
This PR refactors code from `get_info` to easily allow other violation types besides `privacy` and `dependency`. On top of that, it allows outputting per-pack data in CSV format.
That being said, the default output remains being exactly the same as before.
I think the CSV format is very valuable because it can easily be used for getting periodic progress reports and even transform it to other formats via external tools (JSON, markdown table, etc). I'm personally using it to generate a markdown table from it.
Example using default "detail" format and picking dependency and architecture violations:
```
$ bin/packs get_info -t dependency,architecture packs/foo packs/bar packs/baz
There are 58 total inbound dependency violations
There are 20 total inbound architecture violations
There are 171 …
```
=> Support CSV format for `get_info` and allow including any violation types

lib/packs/private.rb, spec/packs_spec.rb, spec/spec_helper.rb
When moving a pack under a parent pack, update `ignored_depedencies` for other packs.
=> Modify ignore dependencies when move_pack_to_parent

lib/packs.rb, lib/packs/cli.rb, spec/packs_spec.rb
Because these options feel like "advanced" things to be aware of when calling these methods, and because they feel like reasonable defaults, we lifted them up from `Packs::CLI` to `Packs`.
=> lift per_file_processors defaults to Packs from Packs::CLI

Gemfile.lock, lib/packs/private.rb, packs.gemspec
In `move_to_parent`, the process of moving a pack is:
1. Create a new `package.yml` in the target location with the attributes of the pack being moved
2. Move the files to the new location using `move_to_pack!`
3. Delete the original `package.yml` for the moved pack
In step 1, we were setting `enforce_privacy` for the new `package.yml` to the value of the original pack's `enforce_dependencies` flag instead of its `enforce_privacy` flag.
I tried to write a spec for this behavior, but when writing package yml the `enforce_privacy` flag was always getting written as `false`... I think because the [privacy extension](https://github.com/rubyatscale/parse_packwerk/blob/main/lib/parse_packwerk.rb#L71-L73) is disabled in the test suite.
=> fix enforce privacy flag when creating new pack in Packs::move_to_parent!

lib/packs/private.rb, spec/packs_spec.rb
If we have a file like this for `packs/fruit`:
`fruit.yml`
```
dependencies:
- packs/orange
ignored_dependencies:
- packs/apple
```
and we move `packs/apple` under the parent `packs/fruit`, we get
```
dependencies:
- packs/orange
- packs/fruit/apple
ignored_dependencies:
- packs/fruit/apple
```
This PR changes `move_to_parent` such that this is now the output:
```
dependencies:
- packs/orange
ignored_dependencies:
- packs/fruit/apple
```
=> Do not add dependency to parent pack if subpack is ignored dependency

Gemfile.lock, lib/packs/private.rb, sorbet/rbi/gems/parse_packwerk@0.20.1.rbi, spec/packs_spec.rb, spec/spec_helper.rb
We need this change to work with the latest parse_packwerk due to https://github.com/rubyatscale/parse_packwerk/pull/35
=> Add violations to ParsePackwerk call

lib/packs/cli.rb, lib/packs/private.rb, lib/packs/user_event_logger.rb
Prefer reading the `public_path` value from the packwerk configuration
=> Remove hard-coded references to 'app/public'

lib/packs.rb, lib/packs/private.rb, spec/packs_spec.rb
`packs` is able to find packs anywhere, as long as those locations are
specified in `packs.yml`.
=> Allow packs to be created anywhere

Gemfile.lock, README.md, lib/packs.rb, lib/packs/cli.rb, lib/packs/private.rb, lib/packs/user_event_logger.rb, packs.gemspec, spec/packs_spec.rb
`move_to_folder` works like `move_to_parent`, except it doesn't treat the destination like pack. It still updates `package.yml`, `package_todo.yml`, and Sorbet files that reference the moved pack, but it does not create a `package.yml` file in the target directory. It also does not modify the `package.yml` if it already exists (e.g., it will not add the moved pack as a dependency).
In addition to the specs, I tested this against the Gusto codebase and the command worked as expected.
=> add the move_to_folder command

Gemfile.lock, lib/packs.rb, lib/packs/cli.rb, lib/packs/private.rb, packs.gemspec, sorbet/rbi/gems/.gitattributes, sorbet/rbi/gems/packs-specification@0.0.10.rbi, sorbet/rbi/gems/parse_packwerk@0.21.0.rbi, spec/packs/private/cli_spec.rb, spec/packs_spec.rb, spec/spec_helper.rb
The `packs` half of https://github.com/rubyatscale/parse_packwerk/pull/39.
This PR adds an `enforce_architecture` flag wherever `enforce_privacy` is used, bringing parity between the two extensions for `packs` functionality (namely, setting these flags in `package.yml` files when packs are created or moved).
=> add enforce_architecture flag wherever enforce_privacy is used

.github/workflows/cd.yml
We're attempting to fix [this](https://github.com/rubyatscale/packs/actions/runs/7224931276) failing CD action on main by updating the publish-rubygems-action step to the latest version, which uses Ruby 3 instead of 2.7.
=> update publish rubygems action to ruby 3

lib/packs/private/file_move_operation.rb, lib/packs/update_references_post_processor.rb, spec/packs_spec.rb
`packs` seems a little confused about what is a pack. Packs are packwerk packages that have additional functionality sprinkled on top. Not all packwerk packages are packs, and thus not all packwerk packages have engine-like structure.
This leads to `packs move` having really surprising behavior when moving files out of a non-pack package, as demonstrated by the regression spec included in this PR. Note that every app has at least one package that is not a pack: The root package. This was already handled as a special case.
`origin_pack = ParsePackwerk.package_from_path(origin_pathname)` exemplifies this incorrect assumption: It fetches a _package_ and then assigns it to a variable called _pack_ and proceeds to make assumptions that don't hold for packages that are not packs. Luckily, …
=> handle (most) packages that are not packs

Gemfile.lock
- Adds the universal-darwin platform to hopefully stop the persistent sorbet-static bundler issues we run into
=> use universal darwin platform

Gemfile.lock, packs.gemspec
https://github.com/rubyatscale/parse_packwerk has been updated to use "layers" instead of "architecture" but `packs` has not yet. When we do update this gem, we can remove the version cap.
=> lock parse packwerk version to <= 0.23.0

Gemfile.lock, lib/packs/private/file_move_operation.rb, packs.gemspec, spec/packs_spec.rb
This PR fixes the following issue, resulting in the expected behavior.
When moving a file to a new pack, the file moves, the corresponding spec moves, and the rubocop TODO file is updated.
Running `bin/packs move packs/product_services/payroll/payroll_agency_onboarding packs/admin/developer_utils/lib/alt_sftp_helper.rb` results in the following diff:
```
modified:   .rubocop_todo.yml
renamed:    packs/admin/developer_utils/lib/alt_sftp_helper.rb -> packs/product_services/payroll/payroll_agency_onboarding/lib/alt_sftp_helper.rb
renamed:    packs/admin/developer_utils/spec/lib/alt_sftp_helper_spec.rb -> packs/product_services/payroll/payroll_agency_onboarding/spec/lib/alt_sftp_helper_spec.rb
```
When moving a file to a new pack, the file moves and the rubocop TODO file is updated.
Running …
=> Fix lib file moves

Gemfile.lock, README.md, lib/packs/configuration.rb, lib/packs/user_event_logger.rb, packs.gemspec, spec/packs_spec.rb
Allows users to specify a README template other than the default template currently defined in `packs`. Also allows users to specify a path to the readme template, or by default the template should be located at `README_TEMPLATE.md`. The README_TODO file currently contains the following text:
```
Welcome to `#{pack_name}`!
If you're the author, please consider replacing this file with a README.md, which may contain:
- What your pack is and does
- How you expect people to use your pack
- Example usage of your pack's public API (which lives in `#{pack_name}/#{ParsePackwerk::DEFAULT_PUBLIC_PATH}`)
- Limitations, risks, and important considerations of usage
- How to get in touch with eng and other stakeholders for questions or issues pertaining to this pack (note: it is recommended to add …
```
=> Make README template customizable

Gemfile.lock, lib/packs/private.rb, lib/packs/user_event_logger.rb, packs.gemspec, spec/packs_spec.rb
When creating a new pack with `packs`, you get `README_TODO.md` and `app/public/TODO.md` files by default. In contrast, `pks` creates only a `README.md` file.
`packs` and `pks` should create the same `README` files. This PR updates `packs` to behave like `pks`. I chose to change `packs` because:
1. The `README_TODO.md` and `app/public/TODO.md` files are often not replaced.
2. Documentation of the public API typically lives in the `README.md` file, so we don't really need a separate file telling you to add to `README.md`.
Note that this change brings `packs` more in line with `pks`, but `pks` still creates a few more folders that `packs` does not (e.g. `spec`).
=> Replace todo files with `README.md`

Gemfile.lock
Updating to use the latest version of `bundler`.
=> bundle with higher version

.github/workflows/cd.yml
Why: To figure out why `packs` is not being deployed.
=> Inline CD pipeline for debugging
